name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Instalar Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Ejecutar tests
      run: npm test
      env:
        CHROME_BIN: /usr/bin/google-chrome
